#!/bin/bash

echo "Content-type: text/html"
echo ""
echo "<html><head><title>GM_SERVER_TESTER"
echo "</title></head><body style='color:white; background-color:black; font-family:monospace'>"
echo "<h3>------------------------</h3>"
echo "<h3>------GM_DIAGNOSTICS----</h3>"
echo "<h3>------------------------</h3>"
echo "Running service  on mumble-server..."
echo "$(service mumble-server status)"
echo "Complete!"
echo "<br/>"
echo "Running diagnostics on web server..."
echo "<br/>"
echo "$(service apache2 status)"
echo "<br/>"
echo "Done."
echo "<br/>"
echo "Full Status:"
echo "<br/>"
echo "$(service --status-all)"
echo "</body><html>"
